name: aue8089pa2
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9.12
    - ipykernel=6.29.5
    - ipywidgets=8.1.5
    - matplotlib=3.9.2
    - numpy=2.0.2
    - pillow=10.4.0
    - scikit-image=0.24.0
    - scipy=1.13.1
    - seaborn=0.13.2
    - ipycanvas=0.13.3
    - tqdm=4.66.5
    - ffmpeg=7.1.0
    - pip:
        - opencv-python==4.10.0.84
        - opencv-contrib-python==4.10.0.84
